services:
  database:
    container_name: "postgres-dev"
    image: "postgres:17.6-alpine3.22"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    profiles: ["tools"]           # ← só sobe com --profile tools
    container_name: "pgadmin-dev"
    image: "dpage/pgadmin4:8"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
